### ISSUE TITLE
"[Expression.Error] We cannot convert the specified value to the specified type" when loading data from a table with "_" in the name

### ISSUE THREAD

**Issue by guenp** [MotherDuck-Open-Source/duckdb-power-query-connector#12]
Repro steps:
1. Create a new table using DuckDB 0.9.2 and insert some values:
```
D create or replace table test_table (i integer, j string);
D insert into test_table (i, j) values (1, 'foo');
D insert into test_table (i, j) values (2, 'bar');
```

2. Load the table into Power BI using instructions from the README.

3. This throws an error:
```
Feedback Type:
Frown (Error)

Error Message:
[Expression.Error] We cannot convert the specified value to the specified type.
```

Note that when creating a table using the following method, the data loads without errors:
```
create or replace table test AS (
    select
        (random() * 10)::INTEGER as customer_integer_field,
        uuid()::VARCHAR as customer_varchar_field
    from generate_series(1, 10) g(x)
);
```

Reported by @kmatt, see [issue](https://github.com/MotherDuck-Open-Source/duckdb-power-query-connector/issues/5#issuecomment-1994562133)

**Comment by guenp** [comment]
It turns out that in this specific repro, it's not the `insert`s that cause the error, but the _underscore in the table name_. If I change the table name to `test` or `testtable`, the data loads without throwing the "we cannot convert ..." error:

```
create or replace table test (i integer, j string);
insert into test (i, j) values (1, 'foo');
insert into test (i, j) values (2, 'bar');
```

<img width="368" alt="image" src="https://github.com/MotherDuck-Open-Source/duckdb-power-query-connector/assets/4041805/923d5339-da39-40ff-8359-5cad8b6a37ff">

**Comment by CurtHagenlocher** [comment]
Because the table name has an underscore (which is a wild card in the spec for SQLColumns) we escape it with a backslash. This apparently causes SQLColumns to return no rows.

**Comment by guenp** [comment]
Thanks @CurtHagenlocher, that was indeed the problem! I added `ESCAPE '\'` to the generated query and that fixed it. I opened a PR to `duckdb`.

**Comment by guenp** [comment]
Closing this because the [PR ](https://github.com/duckdb/duckdb/pull/11432) has been merged but note that it won't be usable with Power BI until https://github.com/duckdb/duckdb/pull/11382 has been merged into the nightly release
