### ISSUE TITLE
add support for anonymous mode 

### ISSUE THREAD

**Issue by djouallah** [MotherDuck-Open-Source/duckdb-power-query-connector#13]
would be nice to add anonymous mode

<img width="559" alt="image" src="https://github.com/MotherDuck-Open-Source/duckdb-power-query-connector/assets/12554469/e0ca0163-3ecb-459e-aee1-ba7298b8dfe5">

**Comment by djouallah** [comment]
do you mind please updating the mez file

**Comment by guenp** [comment]
@djouallah Sure thing, here you go: https://github.com/MotherDuck-Open-Source/duckdb-power-query-connector/releases/download/v0.1.1/DuckDBPowerQueryConnector.mez
