### ISSUE TITLE
"The table has no visible columns and cannot be queried." when reading UTF-8 encoded data with DuckDB 0.10.1+ ODBC driver

### ISSUE THREAD

**Issue by guenp** [MotherDuck-Open-Source/duckdb-power-query-connector#16]
When trying to read UTF-8 encoded data with Power Query, it throws an error:

```
The table has no visible columns and cannot be queried.
```

Trace logs show several `Unknown attribute` errors for `SQLGetInfo` and `SQLColAttribute`.
Diagnostics logs show:

```
ODBC_DuckDB->SQLGetInfo
Unrecognized attribute: 1750
ODBC_DuckDB->SQLGetInfo
Unrecognized attribute: 180
```

Related comment in issue: https://github.com/duckdb/duckdb/issues/10907#issuecomment-2023369306

Steps to reproduce:
1. Create UTF-8 encoded CSV, for example with Python `csv` module:
```
import csv
with open('path\to\test\file.csv', 'w', newline='', encoding='utf-8') as f:
    writer = csv.writer(f, delimiter=';')
    writer.writerow([u'Spam', u'And', u'Eggs', u'And', u'Spam', 1, 2, 3.14])
```
2. Read the CSV file with DuckDB and save to a table
```
duckdb "path\to\test\database.db"
```
```sql
D create table test as (select * from read_csv('path/to/test/file.csv'));
```
4. Load the table with Power Query
```
let
    Database = "path\to\test\database.db",
    OdbcDatasource = DuckDB.Contents(Database)
in
    OdbcDatasource{[Item="test"]}[Data]
```

**Comment by guenp** [comment]
This needs to be fixed in the `duckdb` ODBC driver. PR open [here](https://github.com/duckdb/duckdb/pull/11423).
The missing cases for `SQLGetInfo` are `SQL_DTC_TRANSACTION_COST` and `SQL_RETURN_ESCAPE_CLAUSE`. These are specified in the [ODBC specification](https://github.com/microsoft/ODBC-Specification/blob/master/Windows/inc/sqlext.h).

**Comment by CurtHagenlocher** [comment]
Neither of those attributes are needed by Power Query. I don't think we're even asking for SQL_DTC_TRANSACTION_COST -- maybe that comes from the driver manager? -- and while we are asking for SQL_RETURN_ESCAPE_CLAUSE a failure to implement it has no consequences.

**Comment by guenp** [comment]
> I don't think we're even asking for SQL_DTC_TRANSACTION_COST -- maybe that comes from the driver manager?

@CurtHagenlocher, hmm that is odd, maybe the 1750 `InfoType` is passed incorrectly? `SQL_DTC_TRANSACTION_COST` seems unrelated to UTF-8 encoding to me.

> while we are asking for SQL_RETURN_ESCAPE_CLAUSE a failure to implement it has no consequences.

Yes you are right, in principle we can drop that, but it does lead to a message in the diagnostics log because it exist with `SQL_SUCCESS_WITH_INFO`. I mainly implemented it to clear any confusion for future debugging.

**Comment by CurtHagenlocher** [comment]
In any event, I followed the instructions here and wasn't able to reproduce the problem in either my test environment or in the current version of Power Bi Desktop.

**Comment by guenp** [comment]
@CurtHagenlocher, which version of DuckDB are you using? I reproduced this on DuckDB 0.10.1 with Power BI 2.127.1080.0 (March 2024). I tried running this with DuckDB 0.9.2 and didn't reproduce the issue either.

**Comment by CurtHagenlocher** [comment]
The DLL isn't version-stamped, unfortunately, but I just downloaded it and it has a creation date of February 13.

**Comment by guenp** [comment]
Gotcha, yes so that's the 0.10.0 ODBC driver which doesn't have the `SQL_SUCCESS_WITH_INFO` changes yet that were introduced in [this PR](https://github.com/duckdb/duckdb/pull/8939) so it will just ignore any unrecognized attributes and pass `SQL_SUCCESS`.

**Comment by CurtHagenlocher** [comment]
I tried with the 0.10.1 driver and the call to SqlTables now seems to be returning nothing.

**Comment by guenp** [comment]
@CurtHagenlocher thanks for verifying! Your comment made me realize that maybe the best place to fix this bug is to update `SQLTables` such that it doesn't fail if the return code is `SQL_SUCCESS_WITH_INFO` (see [this line](https://github.com/duckdb/duckdb/blob/e6929cf46eda7a12f55f0fe04bb475913b48d9eb/tools/odbc/src/statement/statement.cpp#L378)) rather than implementing the specific info types. I'll give that a go and update the PR.

**Comment by guenp** [comment]
Confirmed this now works with the [bleeding edge release of duckdb](https://artifacts.duckdb.org/latest/duckdb-binaries-windows.zip).
<img width="741" alt="image" src="https://github.com/MotherDuck-Open-Source/duckdb-power-query-connector/assets/4041805/25f9e55c-f35b-4503-9c60-c811b649b92a">
<img width="583" alt="image" src="https://github.com/MotherDuck-Open-Source/duckdb-power-query-connector/assets/4041805/d0880b2a-42a3-4101-886a-33b999571b07">
