### ISSUE TITLE
chinese text decode error

### ISSUE THREAD

**Issue by msjzs** [MotherDuck-Open-Source/duckdb-power-query-connector#28]
### 1.  create a database file
```
import pandas as pd
import duckdb
db = r"C:\Users\Administrator\Desktop\db.duckdb"
con = duckdb.connect(database=db, read_only=False)
df = pd.DataFrame(data=[('tom',18,),('jerry',20),('我',5),('你',12)],columns=['name','age'])
con.from_df(df).create('tb')
print(con.sql('select *  from tb').df())
con.close()
```

### 2. power-query connect result, some chinese text decode error
![微信截图_20240605112506](https://github.com/MotherDuck-Open-Source/duckdb-power-query-connector/assets/55625895/5bbc5b73-2ef5-4b58-9d51-bb847d9368a8)

### 3. my enviroment
duckdb v1.0.0
odbc  v1.0.0
powerbi desktop 2.129.1229.0 64-bit (2024年5月)

**Comment by guenp** [comment]
Hi @msjzs , thanks for reporting this issue!
We have a workaround for now, could you try and see if it works for you?

## Turning on UTF-8 support in the Language & Region settings

Steps:
1. Open start menu and type "Language settings". Open the "Language & region" settings
2. Click on "Administrative language settings"
3. Click on "Change system locale"
4. Check the "Beta: Use Unicode UTF-8 for worldwide language support" and click OK

![Screenshot 2024-05-03 165950](https://github.com/MotherDuck-Open-Source/duckdb-power-query-connector/assets/4041805/3251d212-0cde-44be-b3a5-68a0d3d434cf)

This prompts Windows to restart.
Next, open Power BI, click on "Options and settings" -> "Options" -> "Data Load" and click the "Clear cache" button.

Now, you should be able to load your UTF-8 encoded database with Power BI directly without using any workarounds:

<img width="653" alt="image" src="https://github.com/MotherDuck-Open-Source/duckdb-power-query-connector/assets/4041805/bc83d199-317b-4142-a180-579a9b9d8a05">

**Comment by msjzs** [comment]
@guenp, it works well, thank you.
