### ISSUE TITLE
Load Iceberg Tables

### ISSUE THREAD

**Issue by jkleinkauff** [MotherDuck-Open-Source/duckdb-power-query-connector#35]
Hey friends,

Would be possible to load iceberg tables within this connector?
(actually, this is a view on top of a iceberg_scan function)

<img width="486" alt="image" src="https://github.com/user-attachments/assets/4de881a5-6afd-485b-ac21-2801db1f9c30">

**Comment by elefeint** [comment]
Are you connecting to plain DuckDB or to MotherDuck using this connector? Most likely, if connecting to "md:", the operation will be done on our backend where the iceberg extension is installed.

**Comment by guenp** [comment]
@jkleinkauff could you also share a repro of what you are trying to run (ideally the DuckDB SQL or Power Query statement you're running)?

**Comment by jkleinkauff** [comment]
In motherduck I have a view similar to

```
create view house_watcher_listings_view_iceberg_full as 
with cte as (
  select _airbyte_data::json as data_json
  from iceberg_scan('s3://bucket/bronze/iceberg/airbyte_raw_listings', skip_schema_inference=True)
)
select
    data_json->'data'->>'id' as id
    , data_json->'data'->>'sourceId' as sourceId
    , etc
from cte
```

Then I configure the connector with my motherduck db and token:
<img width="283" alt="image" src="https://github.com/user-attachments/assets/4c2836ea-4f53-4c98-82d2-7b090c34c565">

The connector will correctly list my tables and views:
<img width="437" alt="image" src="https://github.com/user-attachments/assets/164b00ff-54b3-4486-923e-68fd8e76f6e8">

I select the view I mentioned above and click "Load". I'm not waiting for the preview to complete:
<img width="952" alt="image" src="https://github.com/user-attachments/assets/0fc992da-edd9-47b3-8a8f-8cde27252982">

Sync will start:
<img width="520" alt="image" src="https://github.com/user-attachments/assets/31d4855e-cee7-4b9b-b3df-bd332b2e371f">

After a few seconds, the error pops out:
<img width="528" alt="image" src="https://github.com/user-attachments/assets/41a9903e-b22f-4ccf-a9be-442e8821d40b">



I can provide more information if you need, tbh there is not much to it. I'm just setting my md credentials, selecting the view and trying to load..

**Comment by jkleinkauff** [comment]
@guenp @elefeint I don't want to bother, just check if I may be doing something wrong. Thank you.

**Comment by guenp** [comment]
@jkleinkauff can you try upgrading your `duckdb-odbc` version to the latest one?
see https://duckdb.org/docs/installation/?version=stable&environment=odbc&platform=win&download_method=direct&architecture=x86_64

**Comment by jkleinkauff** [comment]
The config was the same as above, but when trying to list the tables:
<img width="867" alt="image" src="https://github.com/user-attachments/assets/16a70de5-0b50-4186-bb86-5a5e085d7a3b">

**Comment by guenp** [comment]
I was able to reproduce the first error on my end:
<img width="628" alt="image" src="https://github.com/user-attachments/assets/68af4607-1811-44fc-b11b-9707f2a327b4">

```
DataSource.Error: ODBC: ERROR [42000] ODBC_DuckDB->PrepareStmt
Catalog Error: Table Function with name "iceberg_scan" is not in the catalog, but it exists in the iceberg extension.

Please try installing and loading the iceberg extension:
INSTALL iceberg;
LOAD iceberg;


Details:
    DataSourceKind=DuckDB
    DataSourcePath={"database":"md:powerbi"}
    OdbcErrors=[Table]
```

**Comment by guenp** [comment]
@jkleinkauff , tldr; is that you're not doing something wrong, it looks like querying iceberg is currently not supported from the ODBC driver. I will cross post this on https://github.com/duckdb/duckdb-odbc and see if it's possible to add the extension.

**Comment by CurtHagenlocher** [comment]
One thing which might be generically useful is if you could specify a list of extensions in the ODBC connection string to be installed (if necessary) and loaded.

**Comment by guenp** [comment]
@jkleinkauff , great news - we were able to make it work with some changes to the connector. If you set `saas_mode` on you can query the iceberg view. I'll add that option to the connector shortly and post instructions here how to use.
<img width="657" alt="image" src="https://github.com/user-attachments/assets/81ae0cbd-f836-41be-b4ce-b5e13b414a9a">

**Comment by guenp** [comment]
Just pushed a new release, you can find the new .mez file here: https://github.com/MotherDuck-Open-Source/duckdb-power-query-connector/releases/tag/v0.1.4

To set `saas_mode` on, just set it to `true` when you connect:

<img width="520" alt="image" src="https://github.com/user-attachments/assets/f43089c7-4828-4897-8cc0-f2706d97d52d">

Now you can query views that use the `iceberg` extension.
